export const colors = {
  mainColor: "#3D45EE",
  mainColorHoverLight: "#2E36C0",
  mainColorHoverDark: "#5C66FF",
  secondColor: "#B9BCFF",
  starColor: "#FDF0CD",
  starIconColor: "#FFC700",
  startTextColor: "#FFB802",
  wygColor: "#F3F3F3",
  sideBarBgColor: "#1B1B1B",
  redColor: "#EE3D45",
  redColorHoverLight: "#FF5F68",
  successColor: "#45DA10",
  courseIconsSection: "#FF6636",
  courseTextSection: "#6E7485",
  courseStarColor: "#FD8E1F",
  courseConceptColor: "#E1F7E366",
  progressBarCourseColor: "#0DC7B1",
  // ألوان إضافية
  lightBlue: "#E3F2FD",
  lightGreen: "#E8F5E8",
  lightOrange: "#FFF3E0",
  lightPurple: "#F3E5F5",
  lightYellow: "#FFFDE7",
  darkGray: "#2C2C2C",
  mediumGray: "#8E8E93",
};
