import SideBar from "@/components/dashboard-teacher/sideBar/SideBar";
import { fetchUserServer } from "@/lib/fetchUserServer";
import UserProvider from "@/providers/UserProvider";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import React from "react";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "dashboard-teacher",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await fetchUserServer();
  console.log("user : dashboard-teacher", user);
  // if (!user) {
  //   redirect("/login");
  // }

  if (user.role !== "teacher") {
    redirect(`/dashboard-${user.role === "student" ? "user" : user.role}`);
  }
  return (
    <>
      <div className="flex gap-3 p-[20px] h-screen  ">
        <SideBar />
        <ToastContainer />
        <main className="flex-1">
          <UserProvider user={user}>{children}</UserProvider>
        </main>
      </div>
    </>
  );
}
