import SideBar from "@/components/dashboard-teacher/sideBar/SideBar";
import { fetchUserServer } from "@/lib/fetchUserServer";
import UserProvider from "@/providers/UserProvider";
import { Metadata } from "next";
import React from "react";
import { ToastContainer } from "react-toastify";
export const dynamic = "force-dynamic";
export const metadata: Metadata = {
  title: "dashboard-teacher",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await fetchUserServer();
  console.log("currnet user", user);

  // if (!user) {
  //   redirect("/login");
  // }
  
  return (
    <>
      <div className="flex gap-3 p-[20px] h-screen  ">
        <SideBar />
        <ToastContainer />
        <main className="flex-1">
          <UserProvider user={user}>{children}</UserProvider>
        </main>
      </div>
    </>
  );
}
