import SideBar from "@/components/dashboard-user/sideBar/SideBar";
import { Metadata } from "next";
import React from "react";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "dashboard-user",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex gap-3">
        <SideBar />
        <ToastContainer />
        <main className="flex-1">{children}</main>
      </div>
    </>
  );
}
