import SideBar from "@/components/dashboard-user/sideBar/SideBar";
import { fetchUserServer } from "@/lib/fetchUserServer";
import UserProvider from "@/providers/UserProvider";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "dashboard-user",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await fetchUserServer();
  // if (!user) {
  //   redirect("/login");
  // }

  // if (user.role !== "student") {
  //   redirect(`/dashboard-${user.role}`);
  // }

  return (
    <>
      <div className="flex gap-4 p-[20px] h-screen bg-gray-50/50">
        <SideBar />
        <ToastContainer />
        <main className="flex-1 ">
          <UserProvider user={user}>{children}</UserProvider>
        </main>
      </div>
    </>
  );
}
