import SideBar from "@/components/dashboard-admin/sideBar/SideBar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "dashboard-admin",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex gap-3 ">
        <SideBar />
        <main className="flex-1">{children}</main>
      </div>
    </>
  );
}
