import type { Metadata } from "next";
import "./globals.css";
import { fetchUserServer } from "@/lib/fetchUserServer";
import UserProvider from "@/providers/UserProvider";

// import Footer from "@/components/footer/Footer";
// import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "الرئيسية",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await fetchUserServer();
  // if (!user) {
  //   redirect("/login");
  // }

  // if (user.role == "student") {
  //   redirect(`/dashboard-${user.role}`);
  // }
  return (
    <html lang="en" dir="rtl">
      <body className={` antialiased `}>
        <UserProvider user={user}>{children}</UserProvider>
        {/* {children} */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
