import type { Metadata } from "next";
import "./globals.css";

// import Footer from "@/components/footer/Footer";
// import Footer from "@/components/footer/Footer";
export const metadata: Metadata = {
  title: "الرئيسية",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // if (user.role == "student") {
  //   redirect(`/dashboard-${user.role}`);
  // }
  return (
    <html lang="en" dir="rtl">
      <body className={` antialiased `}>
        {children}
        {/* {children} */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
